image: gitpod/workspace-full

tasks:
  - name: Install Terraform
    init: |
      sudo apt-get update
      sudo apt-get install -y wget unzip
      wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      unzip terraform_1.0.0_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version